m = peripheral.wrap("monitor_0")
m.setTextScale(0.5)
m.setBackgroundColor(colors.red)
m.clear()
m.setCursorPos(1,1)
m.print("1\n")
m.print("2\n")
m.print("3\n")
m.print("4\n")
m.print("5\n")
m.print("6\n")
m.print("7\n")
m.print("8\n")
m.print("9\n")
m.print("10\n")
m.print("11\n")
m.print("12\n")